typography_spectrum: 0.6859567076899111
color:
  saturation: 0.12709636450745165
  brandStrength: 0.8279152323957533
  lightness: 0.430838811211288
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  rhythmicContrast: 0.5594328127335757
layout_spectrum: 0.962323076557368
name: MadRez
navigation:
  - name: LinkedIn
    url: www.linkedin.com/in/mrfallah
    type: external
  - name: Facebook
    url: 'http://www.facebook.com/mr.madrez'
    type: external
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: My ideas
description: Come here first
