typography_spectrum: 0
color:
  saturation: 0.1953405
  brandStrength: 0.5716846
  lightness: 0.1451613
  brandColors:
    - '#000000'
    - '#4D97EE'
    - '#FE5C5A'
    - '#3BF9FE'
    - '#E1B2E0'
  rhythmicContrast: 0.8407198
layout_spectrum: 1
name: MadRez
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: My ideas
description: Come here first
